name: personal_finance_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  connectivity_plus: ^7.0.0
  intl: ^0.20.1
  logger: ^2.5.0
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^6.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.7
  extended_image: ^10.0.1
  carousel_slider: ^5.0.0
  share_plus: ^12.0.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  pin_code_fields: ^8.0.1
  package_info_plus: ^9.0.0
  cloud_firestore: ^6.0.3
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1


# Flutter Splash Screen Setup
#
# This configuration helps you create a splash screen for your Flutter project.
#
# Instructions:
# 1. Add the following configuration to your pubspec.yaml file.
# 2. Run the command: dart run flutter_native_splash:create
# 3. If you make any changes to the splash screen configuration, re-run the command.
#
# Current-Configuration:
flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: assets/images/app_logo.png
  android_12:
    image: assets/images/app_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/